/* */

/* Modelagem Básica 
ENTIDADE = TABELA 
CAMPOS = ATRIBUTOS*/

CLIENTE

NOME     - CARACTER (30)
CPF      - NUMERICO (11)
SEXO     - CARACTER (1)
EMAIL    - CARACTER (30)
TELEFONE - CARACTER (30)
ENDERECO - CARACTER (100)


/* PROCESSOS DE MODELAGEM */

/* FASES 01 E 02 - AD ADM DE DADOS*/

MODELAGEM CONCEITUAL - RASCUNHO (PAPEL, WORD, ETC.)
MODELAGEM LÓGICA - QUALQUER PROGRAMA DE MODELAGEM

/* FASE 03 - DBA E AD */

MODELAGEM FÍSICA - SCRIPTS DE BANCO

/* INICIANDO MODELAGEM FÍSICA */

/* CRIANDO BANCO DE DADOS */

CREATE DATABASE PROJETO;

/* CONECTANDO-SE AO BANCO */

USE PROJETO;

/* CRIAR TABELA DE CLIENTES */

CREATE TABLE CLIENTE(
	NOME VARCHAR(30),
	SEXO CHAR(1),
	EMAIL VARCHAR(30),
	CPF INT(11),
	ENDERECO VARCHAR(100),
	TELEFONE VARCHAR(30)
);

/* VERIFICANDO TABELAS DO BANCO */

SHOW TABLES;

/* VERIFICANDO A ESTRUTURA (CAMPOS) DA TABELA */

DESC CLIENTE;

/* SINTAXE BÁSICA DE INSERÇÃO - INSERT INTO TABELA... */

/* COLOCANDO COLUNAS FORMA 1 */

INSERT INTO CLIENTE VALUES ('JOAO', 'M', 'JOÃO@GMAIL.COM', '22111333',  'R CANDIDO DA SILVA 
- SULACAP - RIO DE JANEIRO - RJ', '982020099');

INSERT INTO CLIENTE VALUES ('MARIA', 'F', 'MARIA@HOTMAIL.COM', '23115378',  'R LUIS CARDOSO 
- GUADALUPE - RIO DE JANEIRO - RJ', '982021011');

INSERT INTO CLIENTE VALUES ('FERNANDO', 'M', NULL, '33144332',  'R DOS LIMOEIROS 
- JD. DAS INDUSTRIAS - SAO JOSE DOS CAMPOS - SP', '982020099');

/* COLOCANDO COLUNAS FORMA 2 */

INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF,ENDERECO,TELEFONE) VALUES ('JOAO', 'M', 'JOÃO@GMAIL.COM', '22111333',  'R CANDIDO DA SILVA 
- SULACAP - RIO DE JANEIRO - RJ', '982020099');

INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF,ENDERECO,TELEFONE) VALUES ('MARIA', 'F', 'MARIA@HOTMAIL.COM', '23115378',  'R LUIS CARDOSO 
- GUADALUPE - RIO DE JANEIRO - RJ', '982021011');

INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF,ENDERECO,TELEFONE) VALUES ('FERNANDO', 'M', NULL, '33144332',  'R DOS LIMOEIROS 
- JD. DAS INDUSTRIAS - SAO JOSE DOS CAMPOS - SP', '982020099');

INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF,ENDERECO,TELEFONE) VALUES ('MARCIA', 'F', 'MARCIA@YAHOO.COM', '22341098',
'AV DOS BANDEIRANTES - TUCURUVI - SAO PAULO - SP', '982765542');

INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF,ENDERECO,TELEFONE) VALUES ('FLAVIO', 'M', 'FLAVIO@YAHOO.COM', '21345078',
'R BANDEIRANTES - CEU AZUL - TAUBATE - SP', '985565642');

INSERT INTO CLIENTE (NOME,SEXO,EMAIL,CPF,ENDERECO,TELEFONE) VALUES ('VITOR', 'M', NULL, '213410300',
'AV BRASIL - PADRE MIGUEL - RIO DE JANEIRO - RJ', '981740042');


/* COMANDO SELECT 
SELECAO, PROJECAO E JUNCAO
*/

SELECT NOW() as DATA_HORA;

SELECT 'DANIEL RIBEIRO';

SELECT 'BANCO DE DADOS';

/* ALIAS DE COLUNAS */

SELECT NOME, SEXO, EMAIL FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, ENDERECO FROM CLIENTE;

SELECT SEXO, EMAIL, ENDERECO, NOME FROM CLIENTE;

SELECT NOME, SEXO, EMAIL, NOW() AS DATA_HORA FROM CLIENTE;

/* APENAS PARA FINS ACADÊMICOS */

SELECT * FROM CLIENTE;

/* FILTRANDO DADOS COM WHERE E LIKE*/

SELECT NOME, TELEFONE FROM CLIENTE;

/* FILTRANDO */

SELECT NOME, SEXO FROM CLIENTE
WHERE SEXO = 'M';

SELECT NOME, ENDERECO FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO = 'RJ';

/* UTILIZANDO LIKE - DE FORMA ERRADA - */

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE 'RJ';

/* CARACTER CORINGA % -> QUALQUER COISA*/

SELECT NOME, SEXO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE ENDERECO LIKE '%PADRE MIGUEL%';

/* OPERADORES LÓGICOS */

/* OR = PARA QUE A SAIDA DA QUERY SEJA VERDADEIRA, BASTA QUE APENAS UMA CONDIÇÃO SEJA VERDADEIRA (2 OU MAIS VARIAVEIS)
   AND = PARA QUE A SAIDA DA QUERY SEJA VERDADEIRA, TODAS AS CONDICOES PRECISAM SER VERDADEIRAS */

/* OR - OU */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'F' OR ENDERECO LIKE '%SP';

/* AND - E */

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'M' AND ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE 
SEXO = 'F' AND ENDERECO LIKE '%SP';

/* MOSTRAR TODOS OS BANCOS DE DADOS */

SHOW DATABASES;

/* COUNT(*), GROUP BY, PERFORMANCE COM OPERADORES LÓGICOS */

/* CONTANDO OS REGISTROS DE UMA TABELA */

SELECT COUNT(*) AS 'Quantidade de Registros da Tabela Cliente' 
FROM CLIENTE;

/* OPERADOR GROUP BY */

SELECT SEXO, COUNT(*)
FROM CLIENTE
GROUP BY SEXO;

SELECT ENDERECO, COUNT(*) /*teste*/
FROM CLIENTE
GROUP BY ENDERECO LIKE '%RJ';

SELECT ENDERECO, COUNT(*) /*teste*/
FROM CLIENTE
WHERE ENDERECO LIKE '%RJ';

/* FILTRANDO VALORES NULOS */
/* IS NULL / IS NOT NULL*/

SELECT NOME, SEXO, ENDERECO /*errado*/
FROM CLIENTE
WHERE EMAIL = NULL;

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NULL;

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE SEXO = 'F';

SELECT NOME, SEXO, ENDERECO
FROM CLIENTE
WHERE EMAIL IS NOT NULL;

/* CLÁUSULA UPDATE PARA ATUALIZAR VALORES*/

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'FERNANDO_CAMPOS@HOTMAIL.COM'
WHERE NOME = 'FERNANDO';

UPDATE CLIENTE
SET EMAIL = 'VITOR@HOTMAIL.COM'
WHERE NOME = 'VITOR';

/* DELETANDO REGISTROS */

DELETE FROM CLIENTE;

SELECT * FROM CLIENTE WHERE NOME = 'JOAO';

SELECT COUNT(*) FROM CLIENTE
WHERE NOME = 'JOAO';

DELETE FROM CLIENTE
WHERE NOME = 'JOAO';

/* SELECIONAR E DELETAR UM REGISTRO ESPECÍFICO */
/* SELECIONAR */
SELECT * FROM CLIENTE
WHERE NOME = 'FERNANDO'
AND ENDERECO LIKE '%SP';
/*DELETAR*/
DELETE FROM CLIENTE
WHERE NOME = 'FERNANDO'
AND ENDERECO LIKE '%SP';

/* MODELAGEM */

UPDATE CLIENTE 				/*atualizar*/
SET TELEFONE = '99887766'
WHERE NOME = 'FLAVIO'

SELECT SEXO, COUNT(*) AS QTD
FROM CLIENTE
GROUP BY SEXO;

/* PRIMEIRA FORMA NORMAL */

/*

1 - TODO CAMPO VETORIZADO SE TORNARÁ OUTRA TABELA

[AMARELO, AZUL, LARANJA, VERDE] - CORES
[CA, NY, OK, TX] - SIGLAS DE ESTADOS

2 - TODO CAMPO MULTIVALORADO SE TORNARÁ OUTRA TABELA
QUANDO O CAMPO FOR DIVISÍVEL.

3 - TODA TABELA NECESSITA DE PELO MENOS UM CAMPO QUE
IDENTIFIQUE O REGISTRO COMO ÚNICO.
ISSO SE CHAMA CHAVE PRIMÁRIA, OU PRIMARY KEY (PK)

*** CPF -> DESACONSELHADO

*/


/*DROP DATABASE nome do banco de dados - EXCLUI BANCO DE DADOS*/

/*DROP TABLE nome da tabela - EXCLUI UMA TABELA*/






























