CREATE DATABASE COMERCIO;

USE COMERCIO;

SHOW DATABASES; ---> Opcional

/* MODELAGEM FÍSICA */

CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	SEXO ENUM('M','F') NOT NULL,
	EMAIL VARCHAR(50) UNIQUE,
	CPF VARCHAR(15) UNIQUE
);

/*  IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT, BOA PRÁTICA
	NOME VARCHAR(30) NOT NULL,                 NÃO PODE DEIXAR O CAMPO VAZIO
	SEXO ENUM('M','F') NOT NULL,              DOMÍNIO - CAIXINHA COM INFORMAÇÕES FIXAS
	EMAIL VARCHAR(50) UNIQUE,                 VALOR NÃO PODE SE REPETIR
	CPF VARCHAR(15) UNIQUE,
	TELEFONE VARCHAR(30) NOT NULL UNIQUE */
	
SHOW TABLES;

CREATE TABLE ENDERECO(
	IDENDERECO INT PRIMARY KEY AUTO_INCREMENT,
	RUA VARCHAR(30) NOT NULL,
	BAIRRO VARCHAR(30) NOT NULL,
	CIDADE VARCHAR(30) NOT NULL,
	ESTADO CHAR(2) NOT NULL,
	ID_CLIENTE INT UNIQUE,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

SHOW TABLES;

CREATE TABLE TELEFONE(
	IDTELEFONE INT PRIMARY KEY AUTO_INCREMENT,
	TIPO ENUM('RES','COM','CEL') NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	ID_CLIENTE INT,
	FOREIGN KEY(ID_CLIENTE)
	REFERENCES CLIENTE(IDCLIENTE)
);

SHOW TABLES;

/* CHAVE ESTRANGEIRA É A CHAVE PRIMARIA DE UMA TABELA
QUE VAI ATÉ A OUTRA TABELA PARA FAZER REFERÊNCIA
ENTRE REGISTROS */

/*RELACIONAMENTO 1X1 - TABELA MAIS FRACA (ENDERECO) */

/*RELACIONAMENTO 1XN - CARDINALIDADE N */

/*REFERENCES - LINCA UMA TABELA A OUTRA*/

/*ID_CLIENTE INT UNIQUE - CADA CLIENTE PODERÁ TER
APENAS 1 ENDERECO */

INSERT INTO CLIENTE VALUES(NULL,'JOAO','M','JOAO@IG.COM','4158887795');
INSERT INTO CLIENTE VALUES(NULL,'CARLOS','M','CARLOSA@IG.COM','5464553466');
INSERT INTO CLIENTE VALUES(NULL,'ANA','F','ANA@IG.COM','456545678');
INSERT INTO CLIENTE VALUES(NULL,'CLARA','F',NULL,'5687766856');
INSERT INTO CLIENTE VALUES(NULL,'JORGE','M','JORGE@IG.COM','8756547688');
INSERT INTO CLIENTE VALUES(NULL,'CELIA','M','JCELIA@IG.COM','5767876889');

