CREATE DATABASE ESCOLA;
USE ESCOLA;

CREATE TABLE CURSOS(
	IDCURSO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30) NOT NULL,
	HORAS INT(3) NOT NULL,
	VALOR FLOAT (10,2) NOT NULL
);

/*cadastrar dados*/
INSERT INTO CURSOS VALUES(NULL, 'CIENCIA DE DADOS', 180, 1000.00);
INSERT INTO CURSOS VALUES(NULL, 'FUNDAMENTOS DE BD', 40, 700.00);
/*ler dados*/
SELECT * FROM CURSOS;

DELIMITER #
STATUS

CREATE PROCEDURE CAD_CURSO(P_NOME VARCHAR(30),
						   P_HORAS INT(30), 
						   P_PRECO FLOAT(10,2))
BEGIN
	INSERT INTO CURSOS VALUES(NULL,P_NOME,P_HORAS,P_PRECO);
END
#

DELIMITER ;

CALL CAD_CURSO('BI SQL SERVER',35,3000.00);
CALL CAD_CURSO('POWER BI',20,1000.00);
CALL CAD_CURSO('TABLEAU',30,1200.00);

SELECT * FROM CURSOS;

/* 1 - CRIAR UMA PROCEDURE PARA CONSULTAR CURSOS */
--SEM PARÂMETROS--
DELIMITER #

STATUS

CREATE PROCEDURE CON_CURSO()
BEGIN
	
	SELECT IDCURSO,NOME,HORAS,VALOR
	FROM CON_CURSO;

END
#


