/* CRIANDO BANCO DE DADOS */
CREATE DATABASE LIVRARIA;

/* CONECTANDO-SE AO BANCO */
USE LIVRARIA;

/* CRIAR TABELA DE LIVROS */

CREATE TABLE LIVROS(
	LIVRO VARCHAR(30),
	AUTOR VARCHAR(30),
	SEXO VARCHAR(30),
	PAGINAS VARCHAR(30),
	EDITORA VARCHAR(30),
	VALOR VARCHAR(30),
	UF CHAR(2),
	ANO VARCHAR(30)
);

/* VERIFICANDO TABELAS DO BANCO */

SHOW TABLES;

/* VERIFICANDO A ESTRUTURA (CAMPOS) DA TABELA */

DESC LIVROS;

/* COLOCANDO COLUNAS DA TABELA*/

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('Cavaleiro Real','Ana Claudia','Feminino',
'465','Atlas','49,9','RJ','2009');

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('SQL para leigos','João Nunes','Masculino',
'450','Addison','98','SP','2018');

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('Receitas Caseiras','Celia Tavares','Feminino',
'210','Atlas','45','RJ','2008');

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('Pessoas Efetivas','Eduardo Santos','Masculino',
'390','Beta','78,99','RJ','2018');

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('Habitos Saudáveis','Eduardo Santos','Masculino'
,'630','Beta','150,98','RJ','2019');

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('A Casa Marrom','Hermes Macedo','Masculino',
'250','Bubba','60','MG','2016');

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('Estacio Querido','Geraldo Francisco',
'Masculino','310','Insignia','100','ES','2015');

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('Pra sempre amigas','Leda Silva','Feminino',
'510','Insignia','78,98','ES','2011');

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('Copas Inesqueciveis','Marco Alcantara','Masculino',
'200','Larson','130,98','RS','2018');

INSERT INTO LIVROS (LIVRO,AUTOR,SEXO,PAGINAS,EDITORA,VALOR,UF,ANO) VALUES ('O poder da mente','Clara Mafra','Feminino',	
'120','Continental','56,58','SP','2017');

/* Q-01 */

SELECT * FROM LIVROS;

/* Q-02 */

SELECT LIVRO, EDITORA FROM LIVROS;

/* Q-03 */

SELECT LIVRO, UF FROM LIVROS
WHERE SEXO = 'Masculino';

/* Q-04 */

SELECT LIVRO, PAGINAS FROM LIVROS
WHERE SEXO = 'Feminino';

/* Q-05 */

SELECT LIVRO, VALOR FROM LIVROS
WHERE UF = 'SP';

/* Q-06 */

SELECT AUTOR, SEXO, UF FROM LIVROS
WHERE SEXO = 'Masculino'
AND UF = 'SP'
OR UF = 'RJ';